### ISSUE TITLE
org.mcsoxford.rss.RSSFault: java.text.ParseException: Unparseable date: "Fri, 12 Jun 2015 09:00 EDT" 

### ISSUE THREAD

**Issue by devilmac** [ahorn/android-rss#26]
Hi,

I tried to use your library but I got the error on title.
Can you help me with it?

Thanks.

**Comment by ahorn** [comment]
The way to debug this is to checkout the SimpleDateFormat in the Dates utility class: https://github.com/ahorn/android-rss/blob/master/src/main/java/org/mcsoxford/rss/Dates.java#L32

**Comment by omercii** [comment]
No.

**Comment by ahorn** [comment]
@omercii could you please be more specific. Thank you. The date format is EEE, dd MMM yyyy HH:mm:ss Z. I do not see the seconds in the example.

**Comment by omercii** [comment]
Sorry, last night I was drunk..

**Comment by ahorn** [comment]
@devilmac may I close this issue?
