### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #1 when no internet.

### ISSUE THREAD

**Issue by ashleypeacock** [ahorn/android-rss#28]
Unfortunately not much more information is given although it is caused by this line: 

feed = reader.load(uri);

**Comment by ahorn** [comment]
Could you reproduce this exception with a test case? See https://github.com/ahorn/android-rss/tree/master/src/test/java/org/mcsoxford/rss

**Comment by ashleypeacock** [comment]
Yep sure thing. I am pretty sure this is a bug i've tried multiple ways around this. Just trying to get this imported into Android studio so I can test.
Thanks for your reply :)

**Comment by ashleypeacock** [comment]
Ok,
So 
load(url) was throwing an RSSFault which I wasn't catching as I was only catching RSSExceptions. Added this which prevents the problem with ASyncTask. 

protected RSSFeed doInBackground(String... urls) {
            RSSReader reader = new RSSReader();
            RSSFeed feed = null;
            try {
                feed = reader.load(urls[0]);
                feed.toString();
            }catch(RSSException rs) {
                Log.e(this.getClass().getSimpleName(), "Error gettig list", rs);
            } catch (RSSFault fault) {
                Log.e(this.getClass().getSimpleName(), "Error with RSSFault", fault);
            }
            return feed;
        }

**Comment by ahorn** [comment]
It would make sense if `fault.getCause()` and `fault.getMessage()` indicate that an `IOException` was raised (should you wish to make your error message more precise).
