### ISSUE TITLE
Android Studio implementation

### ISSUE THREAD

**Issue by Baddy247** [ahorn/android-rss#30]
Hi,

I am new to android development. How do I make use of the library in Android Studio? What should I be adding to the build file?

**Comment by ahorn** [comment]
Did this work for you?

**Comment by AndroidCollege** [comment]
hey ahorn,
is it possible to be more specific about how to add this library through gradle or maven ? 
doing
compile 'https://jitpack.io/#ahorn/android-rss'
will clearly not work.

**Comment by ahorn** [comment]
I am afraid I don't use Android Studio. Have a look at Issue #21, perhaps it can help.
