### ISSUE TITLE
Rfc822DateParser is not thread safe

### ISSUE THREAD

**Issue by xmaux72** [ahorn/android-rss#38]
Hi,

I'm using your library to read many rss feeds at a time.
I noted strange dates in my articles and searching the code I noticed that:

/**
   * @see <a href="http://www.ietf.org/rfc/rfc0822.txt">RFC 822</a>
   */
  private static final SimpleDateFormat RFC822 = new SimpleDateFormat(
      "EEE, dd MMM yyyy HH:mm:ss Z", java.util.Locale.ENGLISH);

SimpleDateFormat is NON thread-safe so you can't declare as static
https://stackoverflow.com/questions/6840803/why-is-javas-simpledateformat-not-thread-safe

Thanks for your great work.

**Comment by ahorn** [comment]
Hi @xmaux72. Thanks for the comment. I'd accept a pull request that fixes this issue. Is the other code thread-safe?

**Comment by ahorn** [comment]
Hi @xmaux72 

   For some time now, I wanted to update the README with some contributor information, and references to projects/products that are using android-rss. If you are willing to share any of this information, please feel free to provide the following, or a subset thereof:

* Your name and/or organization you would like to be mentioned;
* The project name, or product, that is using android-rss.

Many thanks again for your contributions!

**Comment by xmaux72** [comment]
https://play.google.com/store/apps/details?id=it.btbmobile.InfoViolaFree
and 
https://play.google.com/store/apps/details?id=it.btbmobile.infotoro

2 news aggregator about italian soccer teams.

feel free to share :)
